#!/usr/bin/env python

def build(bld):
    bld.ap_stlib(
        name='AP_CustomModule',
        ap_vehicle='ArduCopter',
        ap_libraries=[
            'AP_HAL',
            'AP_Param',
            'GCS_MAVLink',
            'SRV_Channel',
        ],
    )